Repository beyond-sw-camp/be04-fin-5team-GRID, pull requests merged in 2024-05, with the labels that each got.

#34 [Feat] 부서 관련 기능 구현
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/GridApplication.java
  grid/src/main/java/org/highfives/grid/department/command/controller/DepartmentController.java
  grid/src/main/java/org/highfives/grid/department/controller/DepartmentController.java
  grid/src/main/java/org/highfives/grid/department/dao/DepartmentMapper.java
  grid/src/main/java/org/highfives/grid/department/dto/DepartmentDTO.java
  grid/src/main/java/org/highfives/grid/department/entity/Department.java
  grid/src/main/java/org/highfives/grid/department/exception/DepartmentNotFoundException.java
  grid/src/main/java/org/highfives/grid/department/query/controller/DepartmentController.java
  grid/src/main/java/org/highfives/grid/department/repository/DepartmentRepository.java
  grid/src/main/java/org/highfives/grid/department/service/DepartmentService.java
  grid/src/main/java/org/highfives/grid/department/service/DepartmentServiceImpl.java
  grid/src/main/resources/application.properties
  grid/src/main/resources/application.yml
  grid/src/main/resources/org/highfives/grid/department/dao/DepartmentMapper.xml
  grid/src/test/java/org/highfives/grid/department/service/DepartmentServiceImplTest.java
Labels: enhancement

#38 [Feat] 단일 직원 등록 기능 구현
  grid-f/grid-project/.gitignore
  grid-f/grid-project/.vscode/extensions.json
  grid-f/grid-project/README.md
  grid-f/grid-project/index.html
  grid-f/grid-project/jsconfig.json
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/public/favicon.ico
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/main.js
  grid-f/grid-project/vite.config.js
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/GridApplication.java
  grid/src/main/java/org/highfives/grid/configure/WebMvcConfig.java
  grid/src/main/java/org/highfives/grid/configure/WebSecurityConfig.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/Employee.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/Gender.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/JoinType.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/WorkType.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/YN.java
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/dto/UserDTO.java
  grid/src/main/java/org/highfives/grid/user/command/repository/UserRepository.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/command/vo/ResAddUserVO.java
  grid/src/main/java/org/highfives/grid/user/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/query/controller/UserController.java
  grid/src/main/resources/application.yaml
  grid/src/test/java/org/highfives/grid/user/command/controller/UserControllerTests.java
  grid/src/test/java/org/highfives/grid/user/command/service/UserServiceImplTests.java
Labels: enhancement

#39 [Feat] 출퇴근 체크, 조회 기능 구현
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/GridApplication.java
  grid/src/main/java/org/highfives/grid/work/command/aggregate/AdTime.java
  grid/src/main/java/org/highfives/grid/work/command/controller/AdTimeController.java
  grid/src/main/java/org/highfives/grid/work/command/dto/AdTimeDTO.java
  grid/src/main/java/org/highfives/grid/work/command/repository/AdTimeRepository.java
  grid/src/main/java/org/highfives/grid/work/command/service/AdTimeService.java
  grid/src/main/java/org/highfives/grid/work/command/service/AdTimeServiceImpl.java
  grid/src/main/java/org/highfives/grid/work/command/vo/ResponseAdTimeVO.java
  grid/src/main/java/org/highfives/grid/work/query/configuration/MybatisConfiguration.java
  grid/src/main/java/org/highfives/grid/work/query/controller/AdTimeController.java
  grid/src/main/java/org/highfives/grid/work/query/dto/AdTimeDTO.java
  grid/src/main/java/org/highfives/grid/work/query/repository/AdTimeMapper.java
  grid/src/main/java/org/highfives/grid/work/query/service/AdTimeService.java
  grid/src/main/java/org/highfives/grid/work/query/service/AdTimeServiceImpl.java
  grid/src/main/java/org/highfives/grid/work/query/vo/ResponseAdTimeListVO.java
  grid/src/main/resources/application.properties
  grid/src/main/resources/application.yml
  grid/src/main/resources/org/highfives/grid/work/query/repository/AdTimeMapper.xml
  grid/src/test/java/org/highfives/grid/work/command/service/AdTimeServiceImplTest.java
  grid/src/test/java/org/highfives/grid/work/query/service/AdTimeServiceImplTest.java
Labels: enhancement

#43 Revert 39 feature/work/ad time
  .github/ISSUE_TEMPLATE/issue--✅feature.md
Labels: enhancement

#44 Feat: 회원 id 로 회원이 속한 부서/팀명과 부서/팀장 정보 조회
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/user/command/aggregate/Employee.java
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/query/config/MapperConfig.java
  grid/src/main/java/org/highfives/grid/user/query/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/query/dto/LeaderInfoDTO.java
  grid/src/main/java/org/highfives/grid/user/query/dto/UserDTO.java
  grid/src/main/java/org/highfives/grid/user/query/repository/UserMapper.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/query/vo/ResFindLeaderVO.java
  grid/src/main/java/org/highfives/grid/user/query/vo/ResFindListVO.java
  grid/src/main/java/org/highfives/grid/user/query/vo/SimpleInfo.java
  grid/src/main/resources/org/highfives/grid/user/query/repository/UserMapper.xml
  grid/src/test/java/org/highfives/grid/user/query/service/UserServiceImplTests.java
Labels: enhancement

#46 Feat: 결재 유형 조회하여 출장 결재 라인 생성
  .idea/be04-fin-5team-GRID.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/GridApplication.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/ApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/ApprovalType.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/BTApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/ChainStatus.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/OApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/controller/ApprovalChainController.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/repository/BTApprovalChainRepository.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainService.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/vo/ReqAddApprovalChainVO.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/vo/ResAddApprovalChainVO.java
  grid/src/main/java/org/highfives/grid/approval_chain/common/dto/ApprovalChainDTO.java
  grid/src/main/java/org/highfives/grid/approval_chain/common/dto/ApprovalTypeDTO.java
  grid/src/main/java/org/highfives/grid/approval_chain/common/dto/BTApprovalChainDTO.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/config/MybatisConfiguration.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/controller/ApprovalChainController.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/service/ApprovalChainService.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/service/ApprovalChainServiceImpl.java
  grid/src/main/java/org/highfives/grid/aprroval_chain/controller/ApprovalChainController.java
  grid/src/main/resources/application.yml
  grid/src/main/resources/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.xml
Labels: enhancement, fix

#59 Feat: 출퇴근 기능 구현
  grid/src/main/java/org/highfives/grid/work/command/aggregate/AdTime.java
  grid/src/main/java/org/highfives/grid/work/command/controller/AdTimeController.java
  grid/src/main/java/org/highfives/grid/work/command/dto/AdTimeDTO.java
  grid/src/main/java/org/highfives/grid/work/command/repository/AdTimeRepository.java
  grid/src/main/java/org/highfives/grid/work/command/service/AdTimeService.java
  grid/src/main/java/org/highfives/grid/work/command/service/AdTimeServiceImpl.java
  grid/src/main/java/org/highfives/grid/work/command/vo/ResponseAdTimeVO.java
  grid/src/main/java/org/highfives/grid/work/query/configuration/MybatisConfiguration.java
  grid/src/main/java/org/highfives/grid/work/query/controller/AdTimeController.java
  grid/src/main/java/org/highfives/grid/work/query/dto/AdTimeDTO.java
  grid/src/main/java/org/highfives/grid/work/query/repository/AdTimeMapper.java
  grid/src/main/java/org/highfives/grid/work/query/service/AdTimeService.java
  grid/src/main/java/org/highfives/grid/work/query/service/AdTimeServiceImpl.java
  grid/src/main/java/org/highfives/grid/work/query/vo/ResponseAdTimeListVO.java
  grid/src/main/resources/org/highfives/grid/work/query/repository/AdTimeMapper.xml
  grid/src/test/java/org/highfives/grid/work/command/service/AdTimeServiceImplTest.java
  grid/src/test/java/org/highfives/grid/work/query/service/AdTimeServiceImplTest.java
Labels: enhancement

#62 Feat: 유저 정보 수정 기능 추가
  grid/src/main/java/org/highfives/grid/department/command/controller/DepartmentController.java
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/Employee.java
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/dto/UserDTO.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
  grid/src/test/java/org/highfives/grid/user/command/service/UserServiceImplTests.java
Labels: enhancement

#66 Feat: 직원 정보 일괄 수정 기능 추가
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/dto/UserDTO.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/query/config/UserMapperConfig.java
  grid/src/main/resources/application.yaml
  grid/src/test/java/org/highfives/grid/user/command/service/UserServiceImplTests.java
Labels: enhancement

#76 Feat: 작성한 업적 평가 조회 기능 구현
  grid/src/main/java/org/highfives/grid/performance_review/query/aggregate/PerformanceReviewGoal.java
  grid/src/main/java/org/highfives/grid/performance_review/query/controller/PerformanceReviewGoalController.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/ApproverDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/EmployeeDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/PerformanceReviewGoalDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/WriterDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalService.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponsePerformanceReviewGoalVO.java
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.xml
  grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalServiceImplTest.java
Labels: enhancement

#68 Feat: 직원 퇴사 시 계정 비활성화, 리스트 조회에서 재직중인 직원만 표시되도록 변경
  grid/src/main/java/org/highfives/grid/user/command/aggregate/Employee.java
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
  grid/src/main/resources/org/highfives/grid/user/query/repository/UserMapper.xml
  grid/src/test/java/org/highfives/grid/user/command/service/UserServiceImplTests.java
Labels: enhancement

#85 Feat: 업적 평가 목표 추가 기능
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/PerformanceReviewGoal.java
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewGoalController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/dto/PerformanceReviewGoalDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewGoalRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/vo/ResponsePerformanceReviewGoalVO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/DetailGoalDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/GoalItemDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseDetailGoalVO.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImplTest.java
Labels: enhancement

#91 Feat: 휴가관련 검색기능 추가
  grid/src/main/java/org/highfives/grid/vacation/query/controller/VacationController.java
  grid/src/main/java/org/highfives/grid/vacation/query/repository/VacationMapper.java
  grid/src/main/java/org/highfives/grid/vacation/query/service/VacationService.java
  grid/src/main/java/org/highfives/grid/vacation/query/service/VacationServiceImpl.java
  grid/src/main/java/org/highfives/grid/vacation/query/vo/DeptSearch.java
  grid/src/main/java/org/highfives/grid/vacation/query/vo/HistorySearch.java
  grid/src/main/java/org/highfives/grid/vacation/query/vo/NameSearch.java
  grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
Labels: enhancement

#98 Feat: 업적 평가 목표 추가 수정 삭제 기능 구현
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/GoalApprovalStatus.java
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/PerformanceReviewGoal.java
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/PerformanceReviewGoalItem.java
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewGoalController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewGoalItemController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/dto/PerformanceReviewGoalItemDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/dto/RequestGoalItemDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewGoalItemRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewGoalRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/vo/RequestGoalItemListVO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/vo/RequestGoalVO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/vo/ResponseDelGoalItemVO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/vo/ResponseGoalAndItemVO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/vo/ResponseGoalItemListVO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/vo/ResponsePerformanceReviewGoalItemVO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/controller/PerformanceReviewGoalController.java
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.xml
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImplTest.java
Labels: enhancement, fix

#99 Feat: 시간 외 근무 결재 관련 기능 구현
  grid/src/main/java/org/highfives/grid/approval/command/aggregate/OvertimeApproval.java
  grid/src/main/java/org/highfives/grid/approval/command/aggregate/OvertimeType.java
  grid/src/main/java/org/highfives/grid/approval/command/aggregate/RWApproval.java
  grid/src/main/java/org/highfives/grid/approval/command/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/command/repository/RWApprovalRepository.java
  grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalService.java
  grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval/command/vo/RWApprovalVO.java
  grid/src/main/java/org/highfives/grid/approval/command/vo/ResApprovalVO.java
  grid/src/main/java/org/highfives/grid/approval/common/dto/OvertimeApprovalDTO.java
  grid/src/main/java/org/highfives/grid/approval/common/dto/RWApprovalDTO.java
  grid/src/main/java/org/highfives/grid/work/query/controller/RwApprovalController.java
  grid/src/main/java/org/highfives/grid/work/query/service/RwApprovalService.java
  grid/src/main/java/org/highfives/grid/work/query/service/RwApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/work/query/vo/ResponseRwListVO.java
Labels: enhancement

#100 Feat: 업적 평가 목표 상태 수정
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewGoalController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImpl.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImplTest.java
Labels: enhancement

#102 Fix: 결재 관련 수정
  grid/src/main/java/org/highfives/grid/approval/command/aggregate/BTApproval.java
  grid/src/main/java/org/highfives/grid/approval/command/aggregate/OvertimeApproval.java
  grid/src/main/java/org/highfives/grid/approval/command/aggregate/RWApproval.java
  grid/src/main/java/org/highfives/grid/approval/command/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval/command/vo/BTApprovalVO.java
  grid/src/main/java/org/highfives/grid/approval/command/vo/OvertimeApprovalVO.java
Labels: fix

#113 Feat: 업적 평가 조회 기능 추가
  grid/src/main/java/org/highfives/grid/performance_review/query/aggregate/PerformanceReview.java
  grid/src/main/java/org/highfives/grid/performance_review/query/controller/PerformanceReviewController.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/DetailPerformanceReviewDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/PerformanceReviewDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/ReviewItemDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/repository/PerformanceReviewMapper.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewService.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseDetailReviewVO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponsePerformanceReviewVO.java
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewMapper.xml
  grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewServiceImplTest.java
Labels: enhancement

#115 Feature/employee/login
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/config/WebMvcConfig.java
  grid/src/main/java/org/highfives/grid/config/WebSecurityConfig.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/DetailGoalDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseDetailGoalVO.java
  grid/src/main/java/org/highfives/grid/security/AuthenticationFilter.java
  grid/src/main/java/org/highfives/grid/security/GridLogoutFilter.java
  grid/src/main/java/org/highfives/grid/security/JwtFilter.java
  grid/src/main/java/org/highfives/grid/security/JwtUtil.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/Employee.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/PrincipalDetails.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/RefreshToken.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/Role.java
  grid/src/main/java/org/highfives/grid/user/command/controller/TokenReissueController.java
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/dto/UserDTO.java
  grid/src/main/java/org/highfives/grid/user/command/repository/TokenReissueRepository.java
  grid/src/main/java/org/highfives/grid/user/command/service/TokenReissueService.java
  grid/src/main/java/org/highfives/grid/user/command/service/TokenReissueServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/command/vo/ReqLogin.java
  grid/src/main/java/org/highfives/grid/user/query/dto/UserDTO.java
  grid/src/main/resources/application.yaml
  grid/src/main/resources/org/highfives/grid/user/query/repository/UserMapper.xml
  grid/src/test/java/org/highfives/grid/user/command/service/UserServiceImplTests.java
Labels: enhancement

#140 Fix: 팀장/부서장 정보 조회 반환값 변경 ( id포함 )
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/main.js
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/Login.vue
  grid/src/main/java/org/highfives/grid/config/WebSecurityConfig.java
  grid/src/main/java/org/highfives/grid/security/GridLogoutFilter.java
  grid/src/main/java/org/highfives/grid/security/JwtFilter.java
  grid/src/main/java/org/highfives/grid/user/query/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserServiceImpl.java
Labels: fix

#131 Feat: 결재 댓글 생성 기능 구현
  grid/src/main/java/org/highfives/grid/approval/command/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/ApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/BTApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/OApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/RWApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/VApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/controller/ApprovalChainController.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainService.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/vo/CommentVO.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/vo/ResAddApprovalChainVO.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/vo/ResApprovalChainVO.java
  grid/src/main/java/org/highfives/grid/approval_chain/common/dto/ApprovalChainDTO.java
  grid/src/main/resources/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.xml
  grid/src/test/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImplTest.java
Labels: enhancement

#141 Feat: 업적 평가 추가 기능 구현
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/PerformanceReviewStatus.java
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/PerformanceReviewType.java
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/PerformanceReview.java
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/dto/PerformanceReviewDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/vo/ResponsePerformanceReviewVO.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImplTest.java
Labels: enhancement

#142 Feat: Header, Sidebar, Footer 화면 구성 구현
  .idea/.gitignore
  .idea/GRID.iml
  .idea/workspace.xml
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/assets/icon1.png
  grid-f/grid-project/src/assets/icon2.png
  grid-f/grid-project/src/assets/logo.png
  grid-f/grid-project/src/assets/profile.png
  grid-f/grid-project/src/components/Footer.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/main.js
  grid-f/grid-project/src/router/index.js
  grid-f/grid-project/vite.config.js
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/config/WebSecurityConfig.java
  grid/src/main/java/org/highfives/grid/department/command/controller/DepartmentController.java
  grid/src/main/java/org/highfives/grid/security/GridLogoutFilter.java
  grid/src/main/resources/application.yaml
Labels: enhancement

#145 Feat: 출장 결재 승인/반려, 시간 외 근무 결재 승인/반려
  grid/src/main/java/org/highfives/grid/approval/command/aggregate/BTApproval.java
  grid/src/main/java/org/highfives/grid/approval/command/aggregate/OvertimeApproval.java
  grid/src/main/java/org/highfives/grid/approval/common/dto/RWApprovalDTO.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/BTApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/OApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/controller/ApprovalChainController.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainService.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/vo/ChainStatusVO.java
  grid/src/main/java/org/highfives/grid/approval_chain/common/dto/ChainDTO.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/service/ApprovalChainService.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/service/ApprovalChainServiceImpl.java
  grid/src/main/resources/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.xml
  grid/src/test/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImplTest.java
Labels: enhancement

#158 Feat: 단축 근무 결재 승인/반려
  grid/src/main/java/org/highfives/grid/approval/command/aggregate/RWApproval.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/RWApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/controller/ApprovalChainController.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/repository/OApprovalChainRepository.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/repository/RWApprovalChainRepository.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainService.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/service/ApprovalChainService.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/service/ApprovalChainServiceImpl.java
  grid/src/main/resources/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.xml
Labels: enhancement

#157 Fix: 조건문 수정
  grid/src/main/java/org/highfives/grid/approval/command/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval/common/dto/OvertimeApprovalDTO.java
Labels: fix

#159 Feat: 휴가 결재 승인/반려
  grid/src/main/java/org/highfives/grid/approval/command/aggregate/VacationApproval.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/VApprovalChain.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/controller/ApprovalChainController.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/repository/RWApprovalChainRepository.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/repository/VApprovalChainRepository.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainService.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
Labels: enhancement

#154 Feat: 업적 평가 생성시 평가 항목 함께 생성
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/PerformanceReview.java
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/PerformanceReviewItem.java
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewItemController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/dto/ModifyPerformanceReviewDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/dto/PerformanceReviewDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/dto/PerformanceReviewItemDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewGoalItemRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewItemRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/vo/RequestPerformanceReviewVO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/vo/ResponseModifyPerformanceReviewVO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalService.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalServiceImpl.java
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.xml
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalServiceImplTest.java
Labels: enhancement, fix

#155 Feat: 부서 전체 정보 수정 기능 및 TDD 추가
  grid/src/main/java/org/highfives/grid/department/command/controller/DepartmentController.java
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentService.java
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
  grid/src/main/java/org/highfives/grid/department/command/vo/ResponseDepartmentListVO.java
  grid/src/test/java/org/highfives/grid/department/command/service/DepartmentServiceImplTest.java
Labels: enhancement

#161 Feat: 결재 열람 상태 변경, 취소 결재 승인
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/approval/command/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalService.java
  grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval/query/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/query/controller/PdfController.java
  grid/src/main/java/org/highfives/grid/approval/query/repository/ApprovalMapper.java
  grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalService.java
  grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
Labels: enhancement

#170 Feat: 종합 업적 평가 생성 기능
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/ReviewGrade.java
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/TotalPerformanceReview.java
  grid/src/main/java/org/highfives/grid/performance_review/command/dto/ReviewGradeDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/dto/TotalPerformanceReviewDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewItemRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/ReviewGradeRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/TotalPerformanceReviewRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/TotalPerformanceReviewService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/TotalPerformanceReviewServiceImpl.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/TotalPerformanceReviewServiceImplTest.java
Labels: enhancement

#175 Fix: 출장 결재 pdf 출력 수정
  grid/business_trip_approval.pdf
  grid/src/main/java/org/highfives/grid/approval/query/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/query/controller/PdfController.java
  grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalService.java
  grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval/query/vo/ApprovalVO.java
  grid/src/main/resources/application.yaml
  grid/src/main/resources/fonts/Sejong hospital Light.ttf
Labels: fix

#177 Feat: 부서 정보 화면, 부서 추가 구현
  grid-f/grid-project/index.html
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/assets/department_icon.png
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Footer.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/router/router.js
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
  grid/src/main/resources/org/highfives/grid/department/query/repository/DepartmentMapper.xml
Labels: enhancement

#181 Feat: 비밀번호 찾기 화면 / 기능 완성
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/main.js
  grid-f/grid-project/src/router/index.js
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/Login/FindId.vue
  grid-f/grid-project/src/views/Login/FindIdResult.vue
  grid-f/grid-project/src/views/Login/FindPwd.vue
  grid-f/grid-project/src/views/Login/FindPwdResult.vue
  grid-f/grid-project/src/views/Login/Login.vue
  grid-f/grid-project/src/views/Login2.vue
  grid/src/main/java/org/highfives/grid/config/WebMvcConfig.java
  grid/src/main/java/org/highfives/grid/notification/controller/NotificationController.java
  grid/src/main/java/org/highfives/grid/notification/service/EmailService.java
  grid/src/main/java/org/highfives/grid/security/AuthenticationFilter.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/Employee.java
  grid/src/main/java/org/highfives/grid/user/command/controller/TokenReissueController.java
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/service/TokenReissueService.java
  grid/src/main/java/org/highfives/grid/user/command/service/TokenReissueServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/command/vo/ReqLoginVO.java
  grid/src/main/java/org/highfives/grid/user/command/vo/ReqResetPwdVO.java
  grid/src/main/java/org/highfives/grid/user/query/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/query/repository/UserMapper.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/query/vo/ResCheckNameVO.java
  grid/src/main/resources/application.yaml
  grid/src/main/resources/org/highfives/grid/user/query/repository/UserMapper.xml
  grid/src/test/java/org/highfives/grid/notification/service/EmailServiceTests.java
  grid/src/test/java/org/highfives/grid/user/command/service/UserServiceImplTests.java
  grid/src/test/java/org/highfives/grid/user/query/service/UserServiceImplTests.java
Labels: enhancement

#178 Feat: 종합 업적 평가 조회 기능
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewGoalController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewItemController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewGoalItemRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewRepository.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemService.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/TotalPerformanceReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/query/aggregate/PerformanceReview.java
  grid/src/main/java/org/highfives/grid/performance_review/query/aggregate/PerformanceReviewGoal.java
  grid/src/main/java/org/highfives/grid/performance_review/query/controller/PerformanceReviewController.java
  grid/src/main/java/org/highfives/grid/performance_review/query/controller/TotalPerformanceReviewController.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/ReviewGradeDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/TotalPerformanceReviewDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.java
  grid/src/main/java/org/highfives/grid/performance_review/query/repository/TotalPerformanceReviewMapper.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/TotalPerformanceReviewService.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/TotalPerformanceReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseDetailTotalVO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseTotalPerformanceReviewVO.java
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/TotalPerformanceReviewMapper.xml
  grid/src/test/java/org/highfives/grid/performance_review/query/service/TotalPerformanceReviewServiceImplTest.java
Labels: enhancement

#200 Feat: 결재 상세 조회
  grid/src/main/java/org/highfives/grid/approval/common/vo/ResApprovalVO.java
  grid/src/main/java/org/highfives/grid/approval/query/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/query/dto/ApprovalEmpDTO.java
  grid/src/main/java/org/highfives/grid/approval/query/repository/ApprovalMapper.java
  grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalService.java
  grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval/query/vo/ApprovalVO.java
  grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
  grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
  grid/src/test/java/org/highfives/grid/vacation/command/service/VacationServiceTest.java
Labels: enhancement

#209 Feat: 출장/시간 외 근무/휴가 목록 화면 구성
  .gitignore
  grid-f/.idea/.gitignore
  grid-f/.idea/gradle.xml
  grid-f/.idea/grid-f.iml
  grid-f/.idea/misc.xml
  grid-f/.idea/modules.xml
  grid-f/.idea/vcs.xml
  grid-f/.idea/workspace.xml
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/components/Approval/ApprovalList.vue
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/Approval/AllApprovalListView.vue
  grid-f/grid-project/src/views/Approval/BTApprovalListView.vue
  grid-f/grid-project/src/views/Approval/OApprovalListView.vue
  grid-f/grid-project/src/views/Approval/VApprovalListView.vue
  grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval/query/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/query/dto/ApprovalEmpDTO.java
  grid/src/main/java/org/highfives/grid/approval/query/repository/ApprovalMapper.java
  grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalService.java
  grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalServiceImpl.java
  grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
  grid/src/main/resources/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.xml
Labels: enhancement

#204 Feat: 인사 정보 메인화면/프로필 화면 완성
  grid-f/grid-project/index.html
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/assets/HR/info-team.png
  grid-f/grid-project/src/assets/HR/time.png
  grid-f/grid-project/src/assets/buttons/add-multi.png
  grid-f/grid-project/src/assets/buttons/add-one.png
  grid-f/grid-project/src/assets/buttons/download.png
  grid-f/grid-project/src/assets/buttons/modify-btn.png
  grid-f/grid-project/src/assets/buttons/plus.png
  grid-f/grid-project/src/assets/buttons/vacation.png
  grid-f/grid-project/src/components/Footer.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/HumanResources/HumanResourcesInfo.vue
  grid-f/grid-project/src/components/HumanResources/WorkVacation.vue
  grid-f/grid-project/src/components/Login/ResetPassword.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/main.js
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/HumanResources/Add.vue
  grid-f/grid-project/src/views/HumanResources/AddMulti.vue
  grid-f/grid-project/src/views/HumanResources/Main.vue
  grid-f/grid-project/src/views/HumanResources/Modify.vue
  grid-f/grid-project/src/views/HumanResources/ModifyMulti.vue
  grid-f/grid-project/src/views/HumanResources/Profile.vue
  grid-f/grid-project/src/views/Login/FindPwdResult.vue
  grid-f/grid-project/src/views/Login/Login.vue
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/query/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/query/dto/DepartmentDTO.java
  grid/src/main/java/org/highfives/grid/user/query/dto/DutiesDTO.java
  grid/src/main/java/org/highfives/grid/user/query/dto/PositionDTO.java
  grid/src/main/java/org/highfives/grid/user/query/dto/TeamDTO.java
  grid/src/main/java/org/highfives/grid/user/query/dto/UserDTO.java
  grid/src/main/java/org/highfives/grid/user/query/repository/UserMapper.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/query/vo/SimpleInfo.java
  grid/src/main/resources/org/highfives/grid/user/query/repository/UserMapper.xml
  grid/src/test/java/org/highfives/grid/user/query/service/UserServiceImplTests.java
  grid/src/test/java/org/highfives/grid/vacation/command/service/VacationServiceTest.java
Labels: enhancement

#211 Feat: 업적 평가 목표 화면 구현
  grid-f/grid-project/package.json
  grid-f/grid-project/src/assets/icons/goal_icon.png
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/PerformanceReview/GoalAddView.vue
  grid-f/grid-project/src/views/PerformanceReview/GoalDetailView.vue
  grid-f/grid-project/src/views/PerformanceReview/GoalListView.vue
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewGoalController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/query/controller/PerformanceReviewGoalController.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseGoalListVO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseGoalVO.java
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.xml
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/query/service/TotalPerformanceReviewServiceImplTest.java
Labels: enhancement

#212 Feat: 출퇴근 조회, 생성 화면 구현
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/AdTime/AdTimeList.vue
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/AdTime/AdTimeAddView.vue
  grid-f/grid-project/src/views/AdTime/AdTimeListView.vue
  grid/src/main/java/org/highfives/grid/work/command/controller/AdTimeController.java
  grid/src/main/java/org/highfives/grid/work/command/repository/AdTimeRepository.java
  grid/src/main/java/org/highfives/grid/work/command/service/AdTimeService.java
  grid/src/main/java/org/highfives/grid/work/command/service/AdTimeServiceImpl.java
  grid/src/main/java/org/highfives/grid/work/command/vo/ResponseAdTimeVO.java
  grid/src/main/java/org/highfives/grid/work/common/dto/AdTimeDTO.java
  grid/src/main/java/org/highfives/grid/work/query/controller/AdTimeController.java
  grid/src/main/java/org/highfives/grid/work/query/service/AdTimeServiceImpl.java
  grid/src/main/java/org/highfives/grid/work/query/vo/ResponseAdTimeListVO.java
  grid/src/main/resources/org/highfives/grid/work/query/repository/AdTimeMapper.xml
  grid/src/test/java/org/highfives/grid/work/command/service/AdTimeServiceImplTest.java
Labels: enhancement

#219 Feat: 결재 상세 화면
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/components/Approval/ApprovalCard.vue
  grid-f/grid-project/src/components/Approval/ApprovalChain.vue
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/Approval/ApprovalDetailView.vue
  grid-f/grid-project/src/views/Approval/BTApprovalListView.vue
Labels: enhancement

#220 Feat: 평가 생성 페이지
  grid-f/grid-project/src/assets/list-check.png
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/components/TeamReview/AddTeamReview.vue
  grid-f/grid-project/src/router/router.js
  grid/src/main/java/org/highfives/grid/review/command/controller/ReviewController.java
  grid/src/main/java/org/highfives/grid/review/command/service/ReviewServiceImpl.java
Labels: enhancement

#222 Fix: 업적 평가 목표, 출퇴근 수정
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/views/AdTime/AdTimeAddView.vue
  grid-f/grid-project/src/views/AdTime/AdTimeListView.vue
  grid-f/grid-project/src/views/PerformanceReview/GoalAddView.vue
  grid-f/grid-project/src/views/PerformanceReview/GoalDetailView.vue
  grid-f/grid-project/src/views/PerformanceReview/GoalListView.vue
  grid/.gitignore
  grid/src/main/resources/application.yaml
Labels: fix

#228 Feat: 결재 요청 목록 화면, 결재 제출 화면
  .gitignore
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/components/Approval/ApprovalList.vue
  grid-f/grid-project/src/components/Approval/BTApprovalForm.vue
  grid-f/grid-project/src/main.js
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/Approval/AllApprovalListView.vue
  grid-f/grid-project/src/views/Approval/BTApprovalListView.vue
  grid-f/grid-project/src/views/Approval/OApprovalListView.vue
  grid-f/grid-project/src/views/Approval/RegistBTApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistOApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistRWApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
  grid-f/grid-project/src/views/Approval/RequiredApprovalListView.vue
Labels: enhancement

#234 Feat: 직원별 댓글 작성
  grid-f/grid-project/src/components/Approval/ApprovalChain.vue
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/Approval/RegistMainView.vue
  grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
  grid-f/grid-project/src/views/Approval/RequiredApprovalListView.vue
  grid/src/main/java/org/highfives/grid/approval/query/repository/ApprovalMapper.java
Labels: enhancement, fix

#235 Feat: User로그인 하였을때 자신의 휴가를 모아볼수있는 화면 구현
  grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
Labels: enhancement

#241 Feat: 부서정보화면 css 수정 및 버튼추가
  grid-f/grid-project/src/assets/newLogo.png
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationDiretlyGive.vue
  grid-f/grid-project/src/components/Vacation/Policy/Modal.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
Labels: enhancement

#244 Feat: 직원별 승인/반려/취소 화면
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/components/Approval/ApprovalChain.vue
  grid-f/grid-project/src/views/Approval/ApprovalDetailView.vue
  grid-f/grid-project/src/views/Approval/RegistBTApprovalView.vue
Labels: enhancement

#246 Feat: Header 부서리스트 draggable 기능 및 프로필 이동 기능 페이지 구현
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/router/router.js
  grid/src/main/java/org/highfives/grid/department/command/aggregate/Department.java
  grid/src/main/java/org/highfives/grid/department/command/aggregate/Team.java
  grid/src/main/java/org/highfives/grid/department/command/controller/DepartmentController.java
  grid/src/main/java/org/highfives/grid/department/command/dto/DepartmentDTO.java
  grid/src/main/java/org/highfives/grid/department/command/dto/TeamDTO.java
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
  grid/src/main/java/org/highfives/grid/department/command/service/TeamServiceImpl.java
  grid/src/main/java/org/highfives/grid/department/query/aggregate/Department.java
  grid/src/main/java/org/highfives/grid/department/query/aggregate/Team.java
  grid/src/main/java/org/highfives/grid/department/query/controller/TeamController.java
  grid/src/main/java/org/highfives/grid/department/query/dto/DepartmentDTO.java
  grid/src/main/java/org/highfives/grid/department/query/dto/TeamDTO.java
  grid/src/main/java/org/highfives/grid/department/query/repository/TeamMapper.java
  grid/src/main/java/org/highfives/grid/department/query/service/TeamService.java
  grid/src/main/java/org/highfives/grid/department/query/service/TeamServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/query/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/query/repository/UserMapper.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/query/vo/ResFindListVO.java
  grid/src/main/resources/org/highfives/grid/department/query/repository/DepartmentMapper.xml
  grid/src/main/resources/org/highfives/grid/department/query/repository/TeamMapper.xml
  grid/src/main/resources/org/highfives/grid/user/query/repository/UserMapper.xml
Labels: enhancement

#253 Feat: 유저 등록 화면 추가
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/assets/HR/csvexample.png
  grid-f/grid-project/src/assets/buttons/dropdown.png
  grid-f/grid-project/src/assets/buttons/guide.png
  grid-f/grid-project/src/assets/buttons/submit.png
  grid-f/grid-project/src/assets/buttons/upload.png
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/HumanResources/ModifyInfo.vue
  grid-f/grid-project/src/main.js
  grid-f/grid-project/src/store.js
  grid-f/grid-project/src/views/HumanResources/AddMulti.vue
  grid-f/grid-project/src/views/HumanResources/Main.vue
  grid-f/grid-project/src/views/HumanResources/ModifyMulti.vue
  grid-f/grid-project/src/views/Login/Login.vue
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
Labels: enhancement

#260 Feat: 모달기능 추가
  grid-f/grid-project/jsconfig.json
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationDiretlyGive.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationInfoModal.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManageModal.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicyModal.vue
  grid-f/package-lock.json
  grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
  grid/src/main/java/org/highfives/grid/vacation/command/vo/GiveVacation.java
Labels: enhancement

#272 Fix: develop 머지 후 발생하는 오류 수정
  grid-f/grid-project/src/views/Approval/AllApprovalListView.vue
  grid-f/grid-project/src/views/Approval/AllWorkListView.vue
  grid-f/grid-project/src/views/Approval/BTApprovalListView.vue
  grid/src/main/java/org/highfives/grid/approval/query/service/PdfServiceImpl.java
  grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
Labels: fix

#270 Feat: 팀 소속직원 리스트 화면, 팀 정보 화면 구현
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Department/Team.vue
  grid-f/grid-project/src/components/Department/TeamMemberList.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/components/TeamReview/AddTeamReview.vue
  grid-f/grid-project/src/components/TeamReview/MyReview.vue
  grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
  grid-f/grid-project/src/components/TeamReview/ReviewList.vue
  grid-f/grid-project/src/router/router.js
  grid/src/main/java/org/highfives/grid/department/query/controller/TeamController.java
  grid/src/main/java/org/highfives/grid/review/query/aggregate/ReviewList.java
  grid/src/main/java/org/highfives/grid/review/query/controller/ReviewController.java
  grid/src/main/java/org/highfives/grid/review/query/dto/ReviewListDTO.java
  grid/src/main/java/org/highfives/grid/review/query/repository/ReviewMapper.java
  grid/src/main/java/org/highfives/grid/review/query/service/ReviewService.java
  grid/src/main/java/org/highfives/grid/review/query/service/ReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/review/query/vo/ResponseReviewListVO.java
  grid/src/main/resources/org/highfives/grid/review/query/repository/ReviewMapper.xml
  grid/src/main/resources/org/highfives/grid/user/query/repository/UserMapper.xml
Labels: enhancement

#271 Fix: 업적평가 유저 체크 하는 기능 추가
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
  grid/src/main/java/org/highfives/grid/performance_review/query/controller/TotalPerformanceReviewController.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/ReviewGradeDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/TotalPerformanceReviewDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/repository/TotalPerformanceReviewMapper.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/TotalPerformanceReviewService.java
  grid/src/main/java/org/highfives/grid/performance_review/query/service/TotalPerformanceReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseDetailTotalVO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseTotalPerformanceReviewVO.java
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/TotalPerformanceReviewMapper.xml
Labels: enhancement

#261 Feat: 근태 관리 풀캘린더 추가
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/AdTime/AdTimeList.vue
  grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/AdTime/WorkCalendarView.vue
Labels: enhancement

#273 Feat: bootstrap 디자인 추가
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
Labels: enhancement

#274 Feat: 프로필 이미지 / 인감 이미지 업로드 / 수정 기능 추가
  grid-f/grid-project/src/assets/defaultProfile.jpg
  grid-f/grid-project/src/assets/defaultSeal.png
  grid-f/grid-project/src/axios.js
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/HumanResources/HumanResourcesInfo.vue
  grid-f/grid-project/src/components/HumanResources/ModifyInfo.vue
  grid-f/grid-project/src/views/HumanResources/AddMulti.vue
  grid-f/grid-project/src/views/HumanResources/Main.vue
  grid-f/grid-project/src/views/HumanResources/Modify.vue
  grid-f/grid-project/src/views/HumanResources/ModifyMulti.vue
  grid-f/grid-project/src/views/HumanResources/Profile.vue
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/config/S3Config.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/EmployeeImg.java
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/dto/ImgDTO.java
  grid/src/main/java/org/highfives/grid/user/command/repository/ImgRepository.java
  grid/src/main/java/org/highfives/grid/user/command/service/ImgService.java
  grid/src/main/java/org/highfives/grid/user/command/service/ImgServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/command/vo/ResImgUploadVO.java
  grid/src/main/resources/application.yaml
  grid/src/test/java/org/highfives/grid/user/command/service/UserServiceImplTests.java
Labels: enhancement

#275 Feat: 결재 목록 화면 디자인
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/components/Approval/ApprovalList.vue
  grid-f/grid-project/src/views/Approval/AllApprovalListView.vue
  grid-f/grid-project/src/views/Approval/AllWorkListView.vue
  grid/src/main/java/org/highfives/grid/approval/query/controller/ApprovalController.java
Labels: enhancement, fix

#276 Fix: 근무 조회, 출퇴근 화면 수정
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/AdTime/AdTimeList.vue
  grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/router/router.js
  grid/src/main/java/org/highfives/grid/work/query/controller/AdTimeController.java
  grid/src/main/java/org/highfives/grid/work/query/repository/AdTimeMapper.java
  grid/src/main/java/org/highfives/grid/work/query/service/AdTimeService.java
  grid/src/main/java/org/highfives/grid/work/query/service/AdTimeServiceImpl.java
  grid/src/test/java/org/highfives/grid/work/query/service/AdTimeServiceImplTest.java
Labels: fix

#277 Fix: 업적평가, 출퇴근 수정
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/router/router.js
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewGoalController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImpl.java
Labels: fix

#278 Feat: 부트스트랩 및 검증기능 추가
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
Labels: enhancement

#279 Fix: 결재 생성 기능 관련 수정
  grid-f/grid-project/src/views/Approval/RegistBTApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistOApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistRWApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
Labels: fix

#281 Fix: 결재 관련 수정
  grid-f/grid-project/src/components/Approval/ApprovalChain.vue
  grid-f/grid-project/src/views/Approval/AllApprovalListView.vue
  grid-f/grid-project/src/views/Approval/ApprovalDetailView.vue
  grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
  grid/src/main/java/org/highfives/grid/approval/query/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/query/repository/ApprovalMapper.java
  grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalService.java
  grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval/query/vo/ApprovalVO.java
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
  grid/src/main/java/org/highfives/grid/approval_chain/query/controller/ApprovalChainController.java
  grid/src/main/java/org/highfives/grid/vacation/command/service/VacationService.java
  grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
  grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
  grid/src/main/resources/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.xml
  grid/src/test/java/org/highfives/grid/vacation/command/service/VacationServiceTest.java
Labels: fix

#280 Feat: 인사 정보 메인 페이지 페이징 처리
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/assets/HR/address.png
  grid-f/grid-project/src/assets/HR/assignedTask.png
  grid-f/grid-project/src/assets/HR/date.png
  grid-f/grid-project/src/assets/HR/duties.png
  grid-f/grid-project/src/assets/HR/email.png
  grid-f/grid-project/src/assets/HR/employeeNumber.png
  grid-f/grid-project/src/assets/HR/name.png
  grid-f/grid-project/src/assets/HR/oldPhone.png
  grid-f/grid-project/src/assets/HR/position.png
  grid-f/grid-project/src/assets/HR/resign.png
  grid-f/grid-project/src/assets/HR/smartPhone.png
  grid-f/grid-project/src/assets/HR/type.png
  grid-f/grid-project/src/assets/buttons/guide.png
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/HumanResources/HumanResourcesInfo.vue
  grid-f/grid-project/src/components/HumanResources/ModifyInfo.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/views/HumanResources/AddMulti.vue
  grid-f/grid-project/src/views/HumanResources/Main.vue
  grid-f/grid-project/src/views/HumanResources/Modify.vue
  grid-f/grid-project/src/views/HumanResources/ModifyMulti.vue
  grid-f/grid-project/src/views/HumanResources/Profile.vue
  grid/src/main/java/org/highfives/grid/user/query/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/query/repository/UserMapper.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserService.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/query/vo/ResFindListVO.java
  grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
  grid/src/main/java/org/highfives/grid/vacation/command/vo/GiveVacation.java
  grid/src/main/resources/application.yaml
  grid/src/main/resources/org/highfives/grid/user/query/repository/UserMapper.xml
  grid/src/test/java/org/highfives/grid/user/query/service/UserServiceImplTests.java
  grid/src/test/java/org/highfives/grid/vacation/command/service/VacationServiceTest.java
Labels: enhancement
