Repository beyond-sw-camp/be04-fin-5team-GRID, pull requests merged in 2024-06, with the labels that each got.

#282 Fix : 멘토링 지적 사항 수정
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/assets/HR/addMulti.png
  grid-f/grid-project/src/assets/HR/fail.png
  grid-f/grid-project/src/assets/HR/fail2.png
  grid-f/grid-project/src/assets/HR/hr.png
  grid-f/grid-project/src/assets/HR/modify-user.png
  grid-f/grid-project/src/components/HumanResources/HumanResourcesInfo.vue
  grid-f/grid-project/src/components/HumanResources/ModifyInfo.vue
  grid-f/grid-project/src/components/Login/ResetPassword.vue
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/HumanResources/Add.vue
  grid-f/grid-project/src/views/HumanResources/AddMulti.vue
  grid-f/grid-project/src/views/HumanResources/Main.vue
  grid-f/grid-project/src/views/HumanResources/Modify.vue
  grid-f/grid-project/src/views/HumanResources/ModifyMulti.vue
  grid-f/grid-project/src/views/HumanResources/Profile.vue
  grid-f/grid-project/src/views/Login/Login.vue
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/query/service/UserServiceImpl.java
  grid/src/main/resources/application.yaml
  grid/src/main/resources/org/highfives/grid/user/query/repository/ImgMapper.xml
Labels: fix

#289 Fix: 업적 평가 css 수정
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
  grid-f/grid-project/src/views/PerformanceReview/Goal/GoalAddView.vue
  grid-f/grid-project/src/views/PerformanceReview/Goal/GoalDetailView.vue
  grid-f/grid-project/src/views/PerformanceReview/Goal/GoalListView.vue
  grid-f/grid-project/src/views/PerformanceReview/Review/FinalPerformanceReviewAddView.vue
  grid-f/grid-project/src/views/PerformanceReview/Review/MidPerformanceReviewAddView.vue
  grid-f/grid-project/src/views/PerformanceReview/Review/PerformanceReviewDetailView.vue
  grid-f/grid-project/src/views/PerformanceReview/Review/PerformanceReviewListView.vue
  grid-f/grid-project/src/views/PerformanceReview/Total/TotalPerformanceReviewDetailView.vue
  grid-f/grid-project/src/views/PerformanceReview/Total/TotalPerformanceReviewListView.vue
Labels: fix

#283 Fix: 페이징기능 수정 및 회원정보 가져오는 기능 수정
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
Labels: enhancement

#291 Feat: 멘토님 피드백 수정 및 기능 추가
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
  grid/src/main/java/org/highfives/grid/vacation/command/entity/VacationType.java
  grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
  grid/src/main/java/org/highfives/grid/vacation/command/vo/ModifyVacationType.java
  grid/src/main/java/org/highfives/grid/vacation/command/vo/RegistVacationType.java
  grid/src/main/java/org/highfives/grid/vacation/query/controller/VacationController.java
  grid/src/main/java/org/highfives/grid/vacation/query/dto/VacationTypeDTO.java
  grid/src/main/java/org/highfives/grid/vacation/query/entity/VacationType.java
  grid/src/main/java/org/highfives/grid/vacation/query/repository/VacationMapper.java
  grid/src/main/java/org/highfives/grid/vacation/query/service/VacationService.java
  grid/src/main/java/org/highfives/grid/vacation/query/service/VacationServiceImpl.java
  grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
Labels: enhancement

#292 Fix: 캘린더 css 수정
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/AdTime/AdTimeList.vue
  grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
  grid-f/grid-project/src/components/Main/Main.vue
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/AdTime/WorkCalendarView.vue
  grid-f/grid-project/src/views/Approval/AllApprovalListView.vue
  grid-f/grid-project/src/views/Main/Main.vue
  grid/src/main/resources/org/highfives/grid/work/query/repository/AdTimeMapper.xml
Labels: fix

#293 Feat: 단축 근무 결재 파일 업로드, 결재 문서 다운로드 기능
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/package.json
  grid-f/grid-project/src/components/Approval/ApprovalCard.vue
  grid-f/grid-project/src/components/Approval/ApprovalChain.vue
  grid-f/grid-project/src/components/Approval/ApprovalList.vue
  grid-f/grid-project/src/main.js
  grid-f/grid-project/src/router/router.js
  grid-f/grid-project/src/views/Approval/AllApprovalListView.vue
  grid-f/grid-project/src/views/Approval/AllWorkListView.vue
  grid-f/grid-project/src/views/Approval/ApprovalDetailView.vue
  grid-f/grid-project/src/views/Approval/BTApprovalListView.vue
  grid-f/grid-project/src/views/Approval/MyApprovalListView.vue
  grid-f/grid-project/src/views/Approval/OApprovalListView.vue
  grid-f/grid-project/src/views/Approval/RWApprovalListView.vue
  grid-f/grid-project/src/views/Approval/RegistBTApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistMainView.vue
  grid-f/grid-project/src/views/Approval/RegistOApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistRWApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
  grid-f/grid-project/src/views/Approval/RequiredApprovalListView.vue
  grid-f/grid-project/src/views/Login/Login.vue
  grid/src/main/java/org/highfives/grid/approval/command/controller/ApprovalController.java
  grid/src/main/java/org/highfives/grid/approval/query/service/PdfServiceImpl.java
Labels: enhancement

#294 Fix: 화면 css 수정 및 DB 변경으로 TDD 수정
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Department/Team.vue
  grid-f/grid-project/src/components/Department/TeamMemberList.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/components/TeamReview/AddTeamReview.vue
  grid-f/grid-project/src/components/TeamReview/MyReview.vue
  grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
  grid-f/grid-project/src/components/TeamReview/ReviewList.vue
  grid/src/test/java/org/highfives/grid/department/command/service/DepartmentServiceImplTest.java
  grid/src/test/java/org/highfives/grid/department/query/service/DepartmentServiceImplTest.java
Labels: fix

#296 Fix: css 수정
  grid-f/grid-project/src/assets/people.png
  grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
  grid-f/grid-project/src/components/Approval/ApprovalChain.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
  grid-f/grid-project/src/components/TeamReview/AddTeamReview.vue
  grid-f/grid-project/src/components/TeamReview/MyReview.vue
  grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
  grid-f/grid-project/src/components/TeamReview/ReviewList.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/views/AdTime/WorkCalendarView.vue
  grid-f/grid-project/src/views/Approval/AllApprovalListView.vue
  grid-f/grid-project/src/views/Approval/AllWorkListView.vue
  grid-f/grid-project/src/views/Approval/ApprovalDetailView.vue
  grid-f/grid-project/src/views/Approval/BTApprovalListView.vue
  grid-f/grid-project/src/views/Approval/OApprovalListView.vue
  grid-f/grid-project/src/views/Approval/RWApprovalListView.vue
  grid-f/grid-project/src/views/Approval/RegistBTApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistMainView.vue
  grid-f/grid-project/src/views/Approval/RegistOApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistRWApprovalView.vue
  grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
Labels: fix

#297 Fix: 출퇴근, 업적 평가 수정
  grid-f/.idea/vcs.xml
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/views/Main/Main.vue
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.xml
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewMapper.xml
  grid/src/main/resources/org/highfives/grid/work/query/repository/AdTimeMapper.xml
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/command/service/TotalPerformanceReviewServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewServiceImplTest.java
  grid/src/test/java/org/highfives/grid/performance_review/query/service/TotalPerformanceReviewServiceImplTest.java
  grid/src/test/java/org/highfives/grid/work/command/service/AdTimeServiceImplTest.java
  grid/src/test/java/org/highfives/grid/work/query/service/AdTimeServiceImplTest.java
Labels: fix

#298 Fix: css 수정 및 조건문 수정
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
  grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
Labels: fix

#299 fix : 버그 수정 및 권한에 따른 기능 분류
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Department/Team.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/components/TeamReview/AddTeamReview.vue
  grid-f/grid-project/src/components/TeamReview/MyReview.vue
  grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
  grid-f/grid-project/src/components/TeamReview/ReviewList.vue
  grid/src/main/java/org/highfives/grid/department/command/controller/DepartmentController.java
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentService.java
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
  grid/src/main/resources/application.yaml
  grid/src/main/resources/org/highfives/grid/department/query/repository/DepartmentMapper.xml
  grid/src/main/resources/org/highfives/grid/department/query/repository/TeamMapper.xml
  grid/src/main/resources/org/highfives/grid/review/query/repository/ReviewMapper.xml
Labels: bug, fix

#305 Feat: 유효시간 연장 및 css 수정
  grid-f/grid-project/src/App.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/HumanResources/HumanResourcesInfo.vue
Labels: enhancement

#307 Fix: css 수정
  grid-f/grid-project/src/views/Approval/MyApprovalListView.vue
  grid-f/grid-project/src/views/Approval/RequiredApprovalListView.vue
Labels: enhancement

#308 Fix : 부서장, 팀장 변경 수정 및 alert 수정
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Department/Team.vue
  grid-f/grid-project/src/components/TeamReview/AddTeamReview.vue
  grid-f/grid-project/src/components/TeamReview/MyReview.vue
  grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
  grid-f/grid-project/src/components/TeamReview/ReviewList.vue
  grid/build.gradle
  grid/src/main/java/org/highfives/grid/department/command/controller/DepartmentController.java
  grid/src/main/java/org/highfives/grid/department/command/controller/TeamController.java
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentService.java
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
  grid/src/main/java/org/highfives/grid/department/command/service/TeamService.java
  grid/src/main/java/org/highfives/grid/department/command/service/TeamServiceImpl.java
Labels: fix

#309 Feat: 중복되는 휴가이름 검증 추가
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
Labels: enhancement

#310 Fix: 멘토님 피드백, 오류 수정
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/AdTime/AdTimeList.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/ReviewGradeDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/ReviewItemDTO.java
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.xml
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewMapper.xml
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/TotalPerformanceReviewMapper.xml
Labels: fix

#311 Fix : 멘토링 피드백 및 부트스트랩 추가
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Department/Team.vue
  grid-f/grid-project/src/components/Department/TeamMemberList.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/Sidebar.vue
  grid-f/grid-project/src/components/TeamReview/MyReview.vue
  grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
  grid/src/main/java/org/highfives/grid/department/command/controller/TeamController.java
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
  grid/src/main/java/org/highfives/grid/department/command/service/TeamService.java
  grid/src/main/java/org/highfives/grid/department/command/service/TeamServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
  grid/src/main/resources/org/highfives/grid/review/query/repository/ReviewMapper.xml
Labels: fix

#312 Fix : 예외처리, 작동 안될시 alert 표시
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Department/Team.vue
  grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
  grid/src/main/java/org/highfives/grid/department/command/repository/DepartmentRepository.java
  grid/src/main/java/org/highfives/grid/department/command/repository/TeamRepository.java
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
  grid/src/main/java/org/highfives/grid/department/command/service/TeamServiceImpl.java
  grid/src/main/java/org/highfives/grid/review/command/service/ReviewServiceImpl.java
  grid/src/main/java/org/highfives/grid/user/command/aggregate/Employee.java
  grid/src/main/java/org/highfives/grid/user/command/repository/UserRepository.java
Labels: bug, fix

#333 Fix: 퇴근 자동 설정, 업적 평가 기간 추가,css 배지 추가
  grid-f/grid-project/src/components/AdTime/AdTimeList.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid/src/main/java/org/highfives/grid/GridApplication.java
  grid/src/main/java/org/highfives/grid/work/command/service/AdSchedulerService.java
Labels: enhancement, fix

#345 Feat: 활성/비활성 버튼 추가 및 모달추가
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
Labels: enhancement

#350 Feat: 가이드 모달 추가
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
  grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
Labels: enhancement

#362 Fix : 버튼위치 수정 /부서장,팀장 수정 및 추가 시 검색기능 /부서 페이징처리 삭제
  grid-f/grid-project/package-lock.json
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Department/Team.vue
Labels: enhancement, fix

#368 Feat: 휴가 사용기한 날짜 검증기능 추가
  grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
Labels: enhancement

#371 Fix : 평가 생성 시 직원 전체에게 동료평가 생성, 부서장 변경 시 팀 변경 수정
  grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
  grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
  grid/src/main/java/org/highfives/grid/review/command/service/ReviewServiceImpl.java
Labels: fix

#373 Fix: 가이드 추가, css 수정, 사번 추가
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/AdTime/AdTimeList.vue
  grid-f/grid-project/src/components/AdTime/AllWorkCalendar.vue
  grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/WriterDTO.java
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.xml
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewMapper.xml
  grid/src/main/resources/org/highfives/grid/performance_review/query/repository/TotalPerformanceReviewMapper.xml
Labels: fix

#374 Fix: 오타수정
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
Labels: fix

#375 fix: css 수정
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/AdTime/AdTimeList.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
Labels: fix

#379 Fix: approver, css
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/ApproverDTO.java
Labels: fix

#380 fix: css 수정
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
Labels: fix

#383 Fix: css 수정
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
Labels: fix

#386 Fix: @Data 제거, 안쓰는 파일 삭제
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid/build/resources/main/org/highfives/grid/work/query/repository/BtApprovalMapper.xml
  grid/build/resources/main/org/highfives/grid/work/query/repository/OvertimeApprovalMapper.xml
  grid/build/resources/main/org/highfives/grid/work/query/repository/RwApprovalMapper.xml
  grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewItemController.java
  grid/src/main/java/org/highfives/grid/performance_review/command/dto/ReviewGradeDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/ApproverDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/DetailGoalDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/EmployeeDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/GoalItemDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/PerformanceReviewGoalDTO.java
  grid/src/main/java/org/highfives/grid/performance_review/query/dto/WriterDTO.java
  grid/src/main/java/org/highfives/grid/work/query/aggregate/RwApproval.java
  grid/src/main/java/org/highfives/grid/work/query/controller/BtApprovalController.java
  grid/src/main/java/org/highfives/grid/work/query/controller/OvertimeApprovalController.java
  grid/src/main/java/org/highfives/grid/work/query/controller/RwApprovalController.java
  grid/src/main/java/org/highfives/grid/work/query/repository/BtApprovalMapper.java
  grid/src/main/java/org/highfives/grid/work/query/repository/OvertimeApprovalMapper.java
  grid/src/main/java/org/highfives/grid/work/query/repository/RwApprovalMapper.java
  grid/src/main/java/org/highfives/grid/work/query/service/BtApprovalService.java
  grid/src/main/java/org/highfives/grid/work/query/service/BtApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/work/query/service/OvertimeApprovalService.java
  grid/src/main/java/org/highfives/grid/work/query/service/OvertimeApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/work/query/service/RwApprovalService.java
  grid/src/main/java/org/highfives/grid/work/query/service/RwApprovalServiceImpl.java
  grid/src/main/java/org/highfives/grid/work/query/vo/ResponseBtListVO.java
  grid/src/main/java/org/highfives/grid/work/query/vo/ResponseOvertimeListVO.java
  grid/src/main/java/org/highfives/grid/work/query/vo/ResponseRwListVO.java
  grid/src/main/resources/org/highfives/grid/work/query/repository/BtApprovalMapper.xml
  grid/src/main/resources/org/highfives/grid/work/query/repository/OvertimeApprovalMapper.xml
  grid/src/main/resources/org/highfives/grid/work/query/repository/RwApprovalMapper.xml
Labels: fix

#394 Refactor: addReviewHistory 메소드 코드 리팩토링 및 프로메테우스 테스트
  grid/src/main/java/org/highfives/grid/review/command/service/ReviewServiceImpl.java
Labels: enhancement

#399 Feat: 휴가 종류별 시간체크 기능 추가
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
  grid/src/main/java/org/highfives/grid/vacation/command/entity/VacationType.java
  grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
  grid/src/main/java/org/highfives/grid/vacation/command/vo/ModifyVacationType.java
  grid/src/main/java/org/highfives/grid/vacation/command/vo/RegistVacationType.java
  grid/src/main/java/org/highfives/grid/vacation/query/dto/VacationTypeDTO.java
  grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
Labels: enhancement

#403 Fix: css수정
  grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
  grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
Labels: fix

#408 Fix/pr m
  grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
  grid-f/grid-project/src/components/AdTime/AllWorkCalendar.vue
  grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
  grid-f/grid-project/src/views/AdTime/WorkCalendarView.vue
  grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/PerformanceReviewItem.java
  grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemServiceImpl.java
Labels: fix

#406 Fix: 날짜계산 오류 수정
  grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
Labels: fix

#412 Feat: 테이블 컬럼 추가/삭제 및 변경개수 가져오는 기능 추가
  grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
  grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
  grid/src/main/java/org/highfives/grid/vacation/command/entity/VacationHistory.java
  grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
  grid/src/main/java/org/highfives/grid/vacation/query/dto/VacationHistoryDTO.java
  grid/src/main/java/org/highfives/grid/vacation/query/entity/VacationHistory.java
  grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
Labels: enhancement

#413 Fix: 멘토링 피드백
  grid-f/grid-project/src/components/Department/Department.vue
  grid-f/grid-project/src/components/Department/Team.vue
  grid-f/grid-project/src/components/Department/TeamMemberList.vue
  grid-f/grid-project/src/components/Header.vue
  grid-f/grid-project/src/components/TeamReview/AddTeamReview.vue
  grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
  grid-f/grid-project/src/components/TeamReview/ReviewList.vue
  grid/build.gradle
  grid/build/resources/main/application.yaml
  grid/build/resources/main/org/highfives/grid/review/query/repository/ReviewMapper.xml
  grid/build/resources/main/org/highfives/grid/vacation/query/repository/VacationMapper.xml
  grid/src/main/java/org/highfives/grid/review/query/aggregate/ReviewEmployeeHistory.java
  grid/src/main/java/org/highfives/grid/review/query/controller/ReviewController.java
  grid/src/main/java/org/highfives/grid/review/query/dto/ReviewEmployeesHistoryDTO.java
  grid/src/main/java/org/highfives/grid/review/query/repository/ReviewMapper.java
  grid/src/main/java/org/highfives/grid/review/query/service/ReviewService.java
  grid/src/main/java/org/highfives/grid/review/query/service/ReviewServiceImpl.java
  grid/src/main/resources/org/highfives/grid/review/query/repository/ReviewMapper.xml
Labels: fix

#418 Fix: 캘린더 more, popover 수정
  grid-f/grid-project/src/components/AdTime/AllWorkCalendar.vue
  grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
  grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
Labels: fix

#422 Fix: 캘린더, 가이드 css 수정
  grid-f/grid-project/src/components/AdTime/AdTimeList.vue
  grid-f/grid-project/src/components/AdTime/AllWorkCalendar.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
  grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
  grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
Labels: fix

#428 Fix : TDD 수정
  grid/build/resources/main/application.yaml
  grid/src/test/java/org/highfives/grid/department/command/service/DepartmentServiceImplTest.java
  grid/src/test/java/org/highfives/grid/department/command/service/TeamServiceImplTest.java
  grid/src/test/java/org/highfives/grid/department/query/service/DepartmentServiceImplTest.java
  grid/src/test/java/org/highfives/grid/department/query/service/TeamServiceImplTest.java
  grid/src/test/java/org/highfives/grid/review/command/service/ReviewServiceImplTest.java
  grid/src/test/java/org/highfives/grid/review/query/service/ReviewServiceImplTest.java
Labels: fix
